// const ADD_FAVORITES = "ADD_FAVORITES";
// const REMOVE_FAVORITES = "REMOVE_FAVORITES";
// const LOGIN_SUCCESS = "LOGIN_SUCCESS";
// const LOGIN_ERROR = "LOGIN_ERROR";
// const ADD_USER = "ADD_USER";
// const DELETE_USER = "DELETE_USER";
// const ADD_WATCHLIST = "ADD_WATCHLIST";
// const REMOVE_WATCHLIST = "REMOVE_WATCHLIST";

// export {
//   ADD_FAVORITES,
//   REMOVE_FAVORITES,
//   LOGIN_ERROR,
//   LOGIN_SUCCESS,
//   DELETE_USER,
//   ADD_USER,
//   REMOVE_WATCHLIST,
//   ADD_WATCHLIST,
// };
